[package]
name = "songwalker_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
songwalker_core = { path = "../songwalker-core" }
base64 = "0.22"
hound = "3.5"
minimp3 = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2.5"
